name: Compilar APK de Kivy

on:
  push:
    branches: [ "principal", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Redireccionar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libsqlite3-dev
        sudo apt-get install -y openjdk-17-jdk unzip zip

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv kivy

    - name: Inicializar Buildozer (Crear spec)
      run: |
        buildozer init
        # Forzar configuraciones básicas limpias y estables
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/android.api = 33/android.api = 33/' buildozer.spec

    - name: Aceptar Licencias de Android SDK de forma automática
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | buildozer android pdm --add-license "android-sdk-license" || true

    - name: Compilar con Buildozer
      run: |
        buildozer -v android debug
      continue-on-error: false

    - name: Subir APK Generado
      uses: actions/upload-artifact@v4
      with:
        name: CalculadoraKivy-APK
        path: bin/*.apk
